fixtures:
  repositories:
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "5.2.0"
    "g_firewall":
      repo: "git://github.com/glorpen/puppet-g_firewall.git"
      ref:  "v0.3.1"
    "firewall":
      repo: "git://github.com/puppetlabs/puppetlabs-firewall.git"
      ref:  "1.15.3"
    "g_server":
      repo: "git://github.com/glorpen/puppet-g_server.git"
      ref:  "v2.0.0"
    "docker":
      repo: "git://github.com/puppetlabs/puppetlabs-docker.git"
      ref:  "v3.6.0"
    "yum":
      repo: "git://github.com/voxpupuli/puppet-yum.git"
      ref:  "v3.1.1"
    "yumrepo_core":
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      ref:  "1.0.3"
    "cron":
      repo: "git://github.com/voxpupuli/puppet-cron.git"
      ref:  "v1.3.1"
    "lvm":
      repo: "git://github.com/puppetlabs/puppetlabs-lvm.git"
      ref:  "1.2.0"
    "mount_core":
      repo: "git://github.com/puppetlabs/puppetlabs-mount_core.git"
      ref:  "1.0.3"
