---
dist: xenial
services:
  - docker
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
  - 'if [ $DEPLOY_TO_FORGE == "yes" ]; then docker run --rm -v $(pwd):/srv glorpen/hub-metadata --print-only -l /srv/README.rst > README.md; fi'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: CHECK="strings:generate:reference" DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: puppetforge
  user: glorpen
  password:
    secure: "L2CmJ/kI2EuXvSIqr5moeqNBc0uiEJlrX79h+qy0HQSpahSFy7NbQisv57Mb7sGlLoFE6xEg7QsT3YLwsghQ/eflTgzDBKrc3RyQQ+x9O7tvMxAUoHtdUJBEKQXhG/mcFNlbNa4xotErk43A6O3iUNXIzD+n+CrMXOgjGhJtRE3NlHXTxsQ1Q5aEa3GG9IxEUVJnkhYki+ifC6FrFDvyJORM7W7GjzPydpO3MpvO8+VHiTgXy1rmqXneDunaoVkOpC/TbQIvf0QmK3RicuEdMlhxpwhEAzi+7MezwJ05Pd8YJI/TREuFc6XCFVR0C4rQI8Xy3RRpUAzh8TPYALOOqfHFRPKn4uXDdoYt0BQZBVuRrvF6GgmEwwqkn1TiJzydSikq8yogWBbRna2JFIZH5KuTP9sOPBGbRHwDhB0/DUy3+dtvEoaof97G5kIy0Ukzp6At48MYg+Al47YQqFnAz0IuNTJS/j0znteuRiHOM8IfEPJ4C/vewXBTnh/OvrABbuS5oisvB6C8WOOAXJj+rISxnBz8NveVwn4ArRFV/NXZDpC4eVKvrciMUdHr77aFBup6QfqyRxUAQz/p2oRJLqeIYjBeM2ILuZefEEfBIPLcKQ4mQyM+brTCpWcbad4ZbTEtb32dvW5rHC4owZjatQc3b1tRg3GeI4Sr5LjHays="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
